apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: domain-based-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/selflearner2025/domain-based-repo.git
        revision: testnew
        directories:
          - path: jobs/*/*   # matches jobs/dev/claims-domain, jobs/qa/violations-domain etc
  template:
    metadata:
      name: '{{path[1]}}-{{path.basename}}-application'   # e.g. dev-claims-domain-application
      labels:
        env: '{{path[1]}}'           # dev, qa, prod
        domain: '{{path.basename}}'  # claims-domain, violations-domain etc
        managed-by: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/selflearner2025/domain-based-repo.git
        targetRevision: testnew
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: camunda          # hardcoded, same for all apps and envs
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true