apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: domain-based-applicationset-multienv
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/selflearner2025/domain-based-repo.git
        revision: withenv
        directories:
          - path: jobs/*/*/*   # matches jobs/dev/claims-domain/claims-management-app
  template:
    metadata:
      name: '{{path[1]}}-{{path[2]}}-{{path.basename}}-application'
      # e.g. dev-claims-domain-claims-management-app-application
      labels:
        env: '{{path[1]}}'           # dev, qa
        domain: '{{path[2]}}'        # claims-domain, violations-domain
        app: '{{path.basename}}'     # claims-management-app, another-claims-app
        managed-by: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/selflearner2025/domain-based-repo.git
        targetRevision: withenv
        path: '{{path}}'             # e.g. jobs/dev/claims-domain/claims-management-app
      destination:
        server: https://kubernetes.default.svc
        namespace: singlenamespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true