apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: domain-based-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/selflearner2025/domain-based-repo.git
        revision: testnew
        directories:
          - path: jobs/*/*
  template:
    metadata:
      name: '{{path.basename}}-application' 
      labels:
        domain: '{{path[1]}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/selflearner2025/domain-based-repo.git
        targetRevision: testnew
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}-namespace'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
         
