apiVersion: v1
kind: ConfigMap
metadata:
  name: contributor-agreement-app-cm-dev
data:
  artifactName: bpmn-poc.tar.gz
  artifactSha256: "changing contributor app again"
  # command sha256sum bpmn-poc.tar.gz
  artifactUrl: "abcd.efgh"
