apiVersion: v1
kind: ConfigMap
metadata:
  name: another-new-domain-management-app-cm-qa
data:
  artifactName: bpmn-poc.tar.gz
  artifactSha256: "change new domain to something else"
  # command sha256sum bpmn-poc.tar.gz
  artifactUrl: "abcd.efgh"
